# Generated by Django 5.0 on 2024-01-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30, verbose_name='Страна производитель')),
                ('firm', models.CharField(max_length=50, verbose_name='Фирма')),
            ],
            options={
                'verbose_name': 'Страна производитель',
                'verbose_name_plural': 'Страны производители',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='desc',
            field=models.TextField(default='', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(verbose_name='цена'),
        ),
    ]
