# Generated by Django 5.0 on 2024-01-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_maker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('delivery_address', models.CharField(max_length=100, verbose_name='Адрес доставки')),
                ('bonus_and_discount', models.IntegerField(null=True, verbose_name='Бонусы и скидка')),
                ('purchased_products', models.ManyToManyField(related_name='Profiles', to='products.product', verbose_name='Купленные товары')),
            ],
            options={
                'verbose_name': 'Имя',
                'verbose_name_plural': 'Имена',
            },
        ),
    ]
