# Generated by Django 5.0 on 2024-01-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_profile_options_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=120, null=True, verbose_name='Категория'),
        ),
    ]
